development: &default
  adapter: postgresql
  database: eg_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

test:
  <<: *default
  database: eg_test