smtp:
  mandrill:
    address: 'smtp.mandrillapp.com'
    port: 587
    enable_starttls_auto: true
    authentication: 'plain'

AWS:
  S3:
    bucket: eg-production
    access_key_id: <%= ENV['aws_access_key_id'] %>
    secret_access_key: <%= ENV['aws_secret_access_key'] %>
    aws_url: http://eg-production.s3.amazonaws.com/
    aws_raw_url: eg-production.s3.amazonaws.com
    end_point: s3-eu-west-1.amazonaws.com