require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClassRoomsController do

  # This should return the minimal set of attributes required to create a valid
  # ClassRoom. As you add validations to ClassRoom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "teacher" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClassRoomsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all class_rooms as @class_rooms" do
      class_room = ClassRoom.create! valid_attributes
      get :index, {}, valid_session
      assigns(:class_rooms).should eq([class_room])
    end
  end

  describe "GET show" do
    it "assigns the requested class_room as @class_room" do
      class_room = ClassRoom.create! valid_attributes
      get :show, {:id => class_room.to_param}, valid_session
      assigns(:class_room).should eq(class_room)
    end
  end

  describe "GET new" do
    it "assigns a new class_room as @class_room" do
      get :new, {}, valid_session
      assigns(:class_room).should be_a_new(ClassRoom)
    end
  end

  describe "GET edit" do
    it "assigns the requested class_room as @class_room" do
      class_room = ClassRoom.create! valid_attributes
      get :edit, {:id => class_room.to_param}, valid_session
      assigns(:class_room).should eq(class_room)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClassRoom" do
        expect {
          post :create, {:class_room => valid_attributes}, valid_session
        }.to change(ClassRoom, :count).by(1)
      end

      it "assigns a newly created class_room as @class_room" do
        post :create, {:class_room => valid_attributes}, valid_session
        assigns(:class_room).should be_a(ClassRoom)
        assigns(:class_room).should be_persisted
      end

      it "redirects to the created class_room" do
        post :create, {:class_room => valid_attributes}, valid_session
        response.should redirect_to(ClassRoom.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved class_room as @class_room" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassRoom.any_instance.stub(:save).and_return(false)
        post :create, {:class_room => { "teacher" => "invalid value" }}, valid_session
        assigns(:class_room).should be_a_new(ClassRoom)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassRoom.any_instance.stub(:save).and_return(false)
        post :create, {:class_room => { "teacher" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested class_room" do
        class_room = ClassRoom.create! valid_attributes
        # Assuming there are no other class_rooms in the database, this
        # specifies that the ClassRoom created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClassRoom.any_instance.should_receive(:update).with({ "teacher" => "" })
        put :update, {:id => class_room.to_param, :class_room => { "teacher" => "" }}, valid_session
      end

      it "assigns the requested class_room as @class_room" do
        class_room = ClassRoom.create! valid_attributes
        put :update, {:id => class_room.to_param, :class_room => valid_attributes}, valid_session
        assigns(:class_room).should eq(class_room)
      end

      it "redirects to the class_room" do
        class_room = ClassRoom.create! valid_attributes
        put :update, {:id => class_room.to_param, :class_room => valid_attributes}, valid_session
        response.should redirect_to(class_room)
      end
    end

    describe "with invalid params" do
      it "assigns the class_room as @class_room" do
        class_room = ClassRoom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassRoom.any_instance.stub(:save).and_return(false)
        put :update, {:id => class_room.to_param, :class_room => { "teacher" => "invalid value" }}, valid_session
        assigns(:class_room).should eq(class_room)
      end

      it "re-renders the 'edit' template" do
        class_room = ClassRoom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassRoom.any_instance.stub(:save).and_return(false)
        put :update, {:id => class_room.to_param, :class_room => { "teacher" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested class_room" do
      class_room = ClassRoom.create! valid_attributes
      expect {
        delete :destroy, {:id => class_room.to_param}, valid_session
      }.to change(ClassRoom, :count).by(-1)
    end

    it "redirects to the class_rooms list" do
      class_room = ClassRoom.create! valid_attributes
      delete :destroy, {:id => class_room.to_param}, valid_session
      response.should redirect_to(class_rooms_url)
    end
  end

end
